export const SpecialistFormFields = {
  lastName: {
    name: 'lastName',
    type: 'text',
    label: 'Last name',
    isRequired: true,
  },
  firstName: {
    name: 'firstName',
    type: 'text',
    label: 'First name',
    isRequired: true,
  },
  surname: {
    name: 'surname',
    type: 'text',
    label: 'Surname',
    isRequired: false,
  },
  specializations: {
    name: 'specializations',
    type: 'text',
    label: 'Specializations',
    isRequired: true,
  },
  gender: {
    name: 'gender',
    type: 'text',
    label: 'Gender',
    isRequired: true,
  },
  yearsOfExperience: {
    name: 'yearsOfExperience',
    type: 'text',
    label: 'Years of experience',
    isRequired: false,
  },
  formatOfWork: {
    name: 'formatOfWork',
    type: 'text',
    label: 'Format of work',
    isRequired: true,
  },
  addresses: {
    name: 'addresses',
    type: null,
    label: 'Addresses',
    isRequired: true,
  },
  fullAddress: {
    name: 'fullAddress',
    type: 'text',
    label: 'Full address',
    isRequired: true,
  },
  nameOfClinic: {
    name: 'nameOfClinic',
    type: 'text',
    label: 'Office name',
    isRequired: false,
  },
  district: {
    name: 'district',
    type: null,
    label: 'District',
    isRequired: true,
  },
  activityTypes: {
    name: 'activityTypes',
    type: null,
    label: 'Activity types',
    isRequired: true,
  },
  isFreeReception: {
    name: 'isFreeReception',
    type: 'checkbox',
    label: 'Free reception',
    isRequired: false,
  },
  description: {
    name: 'description',
    type: 'text',
    label: 'Description',
    isRequired: false,
  },
  phone: {
    name: 'phone',
    type: 'tel',
    label: 'Phone number',
    isRequired: false,
  },
  email: {
    name: 'email',
    type: 'email',
    label: 'Email',
    isRequired: false,
  },
  website: {
    name: 'website',
    type: 'url',
    label: 'Website',
    isRequired: false,
  },
  instagram: {
    name: 'instagram',
    type: 'url',
    label: 'Instagram',
    isRequired: false,
  },
  facebook: {
    name: 'facebook',
    type: 'url',
    label: 'Facebook',
    isRequired: false,
  },
  youtube: {
    name: 'youtube',
    type: 'url',
    label: 'Youtube',
    isRequired: false,
  },
  linkedin: {
    name: 'linkedin',
    type: 'url',
    label: 'LinkedIn',
    isRequired: false,
  },
  tiktok: {
    name: 'tiktok',
    type: 'url',
    label: 'Tiktok',
    isRequired: false,
  },
  viber: {
    name: 'viber',
    type: 'url',
    label: 'Viber',
    isRequired: false,
  },
  telegram: {
    name: 'telegram',
    type: 'url',
    label: 'Тelegram',
    isRequired: false,
  },
};

export const SpecialistFormSections = {
  general: 'Main information',
  details: 'Details',
  addresses: 'Addresses',
  services: 'Services',
  contacts: 'Contact information',
  socialLinks: 'Social networks',
};
